### ISSUE TITLE
Should stacktrace frame filenames be relative?

### ISSUE THREAD

**Issue by jcberquist** [coldbox-modules/sentry#2]
According to the [Stack Trace Interface](https://docs.sentry.io/development/sdk-dev/interfaces/#stack-trace-interface) the `filename` in each frame should be "The relative filepath to the call".  And you can see in their example:
```
"abs_path": "/real/file/name.py",
"filename": "file/name.py"
```
Right now the absolute template path is being used for "filename" and I think this is preventing errors from grouping together when the absolute path differs, even though they are instances of the same error. Now, I am not clear about what about what path the "filename" should be relative to - maybe the webroot for CFML apps - so I am raising this issue as a question.

**Comment by bdw429s** [comment]
> Now, I am not clear about what about what path the "filename" should be relative to

I have the same question-- what exactly it should be relative to. We can process any paths inside the web root but I'm not sure what we'd do with paths outside the web root.  

> preventing errors from grouping together when the absolute path differs, even though they are instances of the same error.

Even if we used relative paths, the same error in two different files still wouldn't be grouped if that were the case since the path would still be different.  I'm not entirely sure that the same error message in different files should be grouped though.

**Comment by jcberquist** [comment]
>  I'm not entirely sure that the same error message in different files should be grouped though.

Agreed, the situation I am thinking of is where the same file is throwing the same error, but since in one case it is on my Windows machine and another it is on a Linux box, it doesn't group together, since the absolute path to that file is different.

**Comment by bdw429s** [comment]
You can send a pull to try and do this if you want.  I'm not convinced it makes much of a difference though.

**Comment by jcberquist** [comment]
Thanks for supporting this @bdw429s!
